
exports.seed = function(knex) {
  return knex('plants').del()
    .then(function () {
      return knex('plants').insert([
        {
          id: 1, 
          common_name: "Monstera", 
          species_name: "Monstera deliciosa", 
          water: "Once a week",
          light: "Bright to medium", 
          temp: "Warm to hot",
          humidity: "Adaptable", 
          soil: "Holds moisture/dense", 
          lvl: "Beginner", 
          notes: "Adaptable but prefers humid, Nutrient rich dense soil that holds moisture", 
          img: "https://ian-montgomery.github.io/images/Plant-images/monstera.png"
        },
        {
          id: 2, 
          common_name: "Fittonia", 
          species_name: "Fittonia albivenis", 
          water: "Once a week", 
          light: "Filtered medium", 
          temp: "Warm to hot", 
          humidity: "High", 
          soil: "Well-draining", 
          lvl: "Intermediate", 
          notes: "Mist regularly", 
          img: "https://ian-montgomery.github.io/images/Plant-images/fittonia.png"
        },
        {
          id: 3,
          common_name: "Yucca", 
          species_name: "Yucca", 
          water: "Only when soil is completely dry", 
          light: "Bright filtered", 
          temp: "Adaptable", 
          humidity: "Low to moderate", 
          soil: "Sandy", 
          lvl: "Beginner", 
          notes: "Light infrequent misting", 
          img: "https://ian-montgomery.github.io/images/Plant-images/yucca.png"
        },
        {
          id: 4,
          common_name: "Peace Lily", 
          species_name: "Spathiphyllum wallisii", 
          water: "Keep moist but not wet", 
          light: "Adaptable", 
          temp: "Cool to warm", 
          humidity: "High", 
          soil: "Well-draining", 
          lvl: "Beginner", 
          notes: "Mist frequently, repot annually", 
          img: "https://ian-montgomery.github.io/images/Plant-images/peace_lilly.png"
        },
        {
          id: 5,
          common_name: "Aloe", 
          species_name: "Aloe Vera", 
          water: "Only when soil is completely dry", 
          light: "Bright filtered", 
          temp: "Adaptable", 
          humidity: "Low", 
          soil: "Well-draining", 
          lvl: "Beginner", 
          notes: "", 
          img: "https://ian-montgomery.github.io/images/Plant-images/aloe_vera.png"
        },
        {
          id: 6,
          common_name: "Rubber Plant", 
          species_name: "Ficus Elastica", 
          water: "Every 1-2 weeks", 
          light: "Bright to medium", 
          temp: "Warm to hot", 
          humidity: "High", 
          soil: "Well-draining", 
          lvl: "Beginner", 
          notes: "If in dry environment mist regularly", 
          img: "https://ian-montgomery.github.io/images/Plant-images/rubber_plant.png"
        },
        {
          id: 7,
          common_name: "Snake Plant", 
          species_name: "Sansevieria trifasciata", 
          water: "Only when soil is completely dry", 
          light: "Bright filtered", 
          temp: "Adaptable", 
          humidity: "Low", 
          soil: "Soilless potting mixture", 
          lvl: "Beginner", 
          notes: "A soilless potting mixture containing organic and inorganic materials instead of soil does wonders for snake plants because they can be prone to rotting. A regular soil mixture will work well too as long as you make sure the mixture is well-drained, free draining soil.", 
          img: "https://ian-montgomery.github.io/images/Plant-images/snake_plant.png"
        },
        {
          id: 8,
          common_name: "English Ivy", 
          species_name: "Hedera helix", 
          water: "Only when soil is completely dry", 
          light: "Bright filtered", 
          temp: "Cool to warm", 
          humidity: "Moderate", 
          soil: "Well-draining", 
          lvl: "Intermediate", 
          notes: "Like moist environments but not direct misting. Try adding pebbles to a saucer, then add water. Set your ivy on the pebbles and the water will evaporate, raising the humidity around the plant", 
          img: "https://ian-montgomery.github.io/images/Plant-images/english_ivy.png"
        },
        {
          id: 9,
          common_name: "Maidenhair fern", 
          species_name: "Adiantum", 
          water: "Daily", 
          light: "Filtered medium", 
          temp: "Warm", 
          humidity: "High", 
          soil: "Well-draining", 
          lvl: "Intermediate - advanced", 
          notes: "Mist frequently and set on a water-filled pebble tray. Doesn't like to be even slighty dry so commit to checking whether watering is required everyday",
          img: "https://ian-montgomery.github.io/images/Plant-images/maidenhair_fern.png"
        },
        {
          id: 10,
          common_name: "String Of Pearls", 
          species_name: "Senecio rowleyanus", 
          water: "Only when soil is completely dry", 
          light: "Bright filtered", 
          temp: "Adaptable", 
          humidity: "Moderate to high", 
          soil: "Well-draining", 
          lvl: "Beginner", 
          notes: "", 
          img: "https://ian-montgomery.github.io/images/Plant-images/string_of_pearls.png"
        },
        {
          id: 11,
          common_name: "Madagascar dragon tree", 
          species_name: "Dracaena Marginata", 
          water: "Keep moist but not wet", 
          light: "Bright filtered", 
          temp: "Warm", 
          humidity: "Moderate", 
          soil: "Well-draining", 
          lvl: "Beginner", 
          notes: "To keep moist set pot onto a tray filled with pebbles", 
          img: "https://ian-montgomery.github.io/images/Plant-images/madagascar_dragon.png"
        },
        {
          id: 12,
          common_name: "Tillandsia (air plants)", 
          species_name: "Epiphytes or bromeliads", 
          water: "Every 1-2 weeks", 
          light: "Bright filtered", 
          temp: "Adaptable", 
          humidity: "Moderate", 
          soil: "None", 
          lvl: "Intermediate", 
          notes: "Occasionally soak in room temp tap water for 10mins, then gently shake excess water from your plant. Turn it upside down and place it on a towel to dry in a bright space. This is very important! Air plants will quickly rot if they are allowed to stand in excess water for too long without drying. Regular misting is also encouraged", 
          img: "https://ian-montgomery.github.io/images/Plant-images/air_plant.png"
        },
        {
          id: 13,
          common_name: "Devil’s Ivy", 
          species_name: "Epipremnum pinnatum", 
          water: "Once a week", 
          light: "Bright filtered", 
          temp: "Adaptable", 
          humidity: "Moderate", 
          soil: "Well-draining", 
          lvl: "", 
          notes: "Water whenever the top inch or two of soil feels dry", 
          img: "https://ian-montgomery.github.io/images/Plant-images/devils_ivy.png"
        },
        {
          id: 14,
          common_name: "Fiddle Leaf Fig", 
          species_name: "Ficus lyrata", 
          water: "Only when soil is completely dry", 
          light: "Bright filtered", 
          temp: "Warm to hot", 
          humidity: "Moderate", 
          soil: "Well-draining", 
          lvl: "Intermediate - Advanced", 
          notes: "", 
          img: "https://ian-montgomery.github.io/images/Plant-images/fiddle_leaf.png"
        },
        {
          id: 15,
          common_name: "Zanzibar Gem", 
          species_name: "Zamioculcas zamifolia", 
          water: "Only when soil is completely dry", 
          light: "Adaptable", 
          temp: "Warm to hot", 
          humidity: "High", 
          soil: "Well-draining", 
          lvl: "", 
          notes: "Prefers low light conditions but will thrive in indirect bright light as well", 
          img: "https://ian-montgomery.github.io/images/Plant-images/zanzibar_gem.png"
        },
        {
          id: 16,
          common_name: "Succulents", 
          species_name: "Echeverias", 
          water: "Once every 2 weeks", 
          light: "Bright direct", 
          temp: "Warm to hot", 
          humidity: "Moderate", 
          soil: "Well-draining", 
          lvl: "Beginner", 
          notes: "", 
          img: "https://ian-montgomery.github.io/images/Plant-images/succulent.png"
        },
        {
          id: 17,
          common_name: "Sweetheart Plant", 
          species_name: "Hoya kerrii", 
          water: "Only when soil is completely dry", 
          light: "Adaptable", 
          temp: "Warm to hot", 
          humidity: "Adaptable", 
          soil: "Well-draining", 
          lvl: "", 
          notes: "Can be in sunny and shady spots, but dislikes direct sun in summer.", 
          img: "https://ian-montgomery.github.io/images/Plant-images/sweetheart.png"
        },
        {
          id: 18,
          common_name: "Spider Plant", 
          species_name: "Chlorophytum comosum", 
          water: "Keep moist but not wet", 
          light: "Bright filtered", 
          temp: "Adaptable", 
          humidity: "High", 
          soil: 'Well-draining', 
          lvl: "Beginner", 
          notes: "", 
          img: "https://ian-montgomery.github.io/images/Plant-images/spider_plant.png"
        },
        {
          id: 19,
          common_name: "Pink Bubbles", 
          species_name: "Pink callisia repens", 
          water: "Keep moist but not wet", 
          light: "Bright filtered", 
          temp: "Warm to hot", 
          humidity: "High", 
          soil: "Well-draining", 
          lvl: "", 
          notes: "", 
          img: "https://ian-montgomery.github.io/images/Plant-images/pink_bubbles.png"
        },
        {
          id: 20,
          common_name: "Silver Lady Fern", 
          species_name: "Blechnum gibbum", 
          water: "Keep moist but not wet", 
          light: "Bright filtered", 
          temp: "Adaptable", 
          humidity: "Moderate to high", 
          soil: "Well-draining", 
          lvl: "", 
          notes: "The Silver Lady Fern is an air purifier! She requires high humidity during her growth period", 
          img: "https://ian-montgomery.github.io/images/Plant-images/silver_lady_fern.png"
        },
      ]);
    });
};
