
exports.seed = function(knex) {
  return knex('plants').del()
    .then(function () {
      return knex('plants').insert([
        {
          id: 1, 
          common_name: 'Monstera', 
          species_name: 'Monstera deliciosa', 
          water: '', light: 'bright spot, indirect sunlight', 
          temp: '', humidity: 'adaptable, likes a mist spray once a week', 
          soil: '', 
          lvl: 'beginner', 
          more: '', 
          img: ''
        },
        {
          id: 2, 
          common_name: 'Fittonia', 
          species_name: '', 
          water: '', 
          light: '', 
          temp: '', 
          humidity: '', 
          soil: '', 
          lvl: '', 
          more: '', 
          img: ''
        },
        {
          id: 3,
          common_name: 'Yucca', 
          species_name: '', 
          water: '', 
          light: '', 
          temp: '', 
          humidity: '', 
          soil: '', 
          lvl: '', 
          more: '', 
          img: ''
        },
        {
          id: 4,
          common_name: 'Peace Lily', 
          species_name: 'Spathiphyllum wallisii', 
          water: 'keep moist, but not wet', 
          light: 'bright filtered light to full-shade', 
          temp: 'all', 
          humidity: '', 
          soil: 'moist, rich, free-draining', 
          lvl: 'beginner', 
          more: '', 
          img: ''
        },
        {
          id: 5,
          common_name: 'Aloe', 
          species_name: 'Aloe Vera', 
          water: 'minimal - let dry between watering', 
          light: 'full sun', 
          temp: '', 
          humidity: '', 
          soil: 'needs a soil with excellent drainage', 
          lvl: '', 
          more: '', 
          img: ''
        },
        {
          id: 6,
          common_name: 'Rubber Plant', 
          species_name: 'Ficus Elastica', 
          water: 'regularly -keep soil moist', 
          light: 'bright, indirect light', 
          temp: 'warm', 
          humidity: 'regularly mist', 
          soil: 'well-drained soil', 
          lvl: 'beginner', 
          more: '', 
          img: ''
        },
        {
          id: 7,
          common_name: 'Snake Plant', 
          species_name: 'Sansevieria trifasciata', 
          water: 'water when soil completely dry', 
          light: 'no direct sun', 
          temp: 'cool', 
          humidity: 'low', 
          soil: 'free draining soil', 
          lvl: 'beginner', 
          more: '', 
          img: ''
        },
        {
          id: 8,
          common_name: 'English Ivy', 
          species_name: 'Hedera helix', 
          water: 'dont overwater, keep one inch topsoil dry', 
          light: 'bright filtered to low ligh', 
          temp: 'consistent room temperature', 
          humidity: 'moist', 
          soil: 'well-drained', 
          lvl: '', 
          more: '', 
          img: ''
        },
        {
          id: 9,
          common_name: 'Maidenhair fern', 
          species_name: 'Adiantum', 
          water: 'regular', 
          light: 'filtered light', 
          temp: 'warm', 
          humidity: 'moist', 
          soil: '', 
          lvl: 'medium-advanced', 
          more: 'ideal for bathrooms', 
          img: ''
        },
        {
          id: 10,
          common_name: 'String Of Pearls', 
          species_name: 'Senecio rowleyanus', 
          water: 'fortnightly', 
          light: 'bright', 
          temp: '', 
          humidity: '', 
          soil: '', 
          lvl: 'beginner', 
          more: '', 
          img: ''
        },
        {
          id: 11,
          common_name: 'Madagascar dragon tree', 
          species_name: 'D. marginata', 
          water: 'monthly', 
          light: '', 
          temp: 'room', 
          humidity: '', 
          soil: '', 
          lvl: '', 
          more: 'air purifier', 
          img: ''
        },
        {
          id: 12,
          common_name: 'Tillandsia (air plants)', 
          species_name: 'epiphytes or bromeliads', 
          water: 'mist or dunk rarely', 
          light: 'bright, indirect light', 
          temp: '', 
          humidity: 'mid', 
          soil: 'no soil', 
          lvl: 'beginner', 
          more: 'obtains water and nutrients from the air', 
          img: ''
        },
        {
          id: 13,
          common_name: 'Devil’s Ivy', 
          species_name: 'Epipremnum pinnatum', 
          water: 'Approximately once a week or when the top inch or two of soil feels dry', 
          light: 'Situate it in an area that receives filtered sunlight or bright artificial light', 
          temp: '15°C-29°C', 
          humidity: 'Does well at normal (about 40% - 60%) humidity levels', 
          soil: 'An all-purpose, peaty potting mix that drains well', 
          lvl: '', 
          more: '', 
          img: ''
        },
        {
          id: 14,
          common_name: 'Fiddle Leaf Fig', 
          species_name: 'Ficus lyrata', 
          water: 'Allow the potting mix or soil to dry out between each watering', 
          light: 'Requires bright, filtered light', 
          temp: '>16°C', 
          humidity: 'Aim for a humidity level between 30% and 65%.', 
          soil: 'Fast draining, well aerated soils are ideal', 
          lvl: 'Intermediate - Advanced', 
          more: '', 
          img: ''
        },
        {
          id: 15,
          common_name: 'Zanzibar Gem', 
          species_name: 'Zamioculcas zamifolia', 
          water: 'Let the soil dry out in between waterings so as to ensure the stems don\'t rot, water less in the cooler months', 
          light: 'It’s happy in low light conditions but will thrive in indirect bright light', 
          temp: '>16°C', 
          humidity: 'Prefers a humid environment for optimal growth', 
          soil: 'Use a good quality potting mix that is fast draining', 
          lvl: '', 
          more: '', 
          img: ''
        },
        {
          id: 16,
          common_name: 'succulents', 
          species_name: 'echeverias', 
          water: 'once per fortnight', 
          light: 'direct', 
          temp: 'warm', 
          humidity: 'mid', 
          soil: 'well-drained', 
          lvl: 'Beginner', 
          more: '', 
          img: ''
        },
        {
          id: 17,
          common_name: 'Sweetheart Plant', 
          species_name: 'Hoya kerrii', 
          water: 'Wait until the soil has dried out a little and then water again', 
          light: 'Will thrive in both sunny and shady spots, but dislikes direct sun in summer. An east or west facing window suits it', 
          temp: '18°C - 27°C', 
          humidity: 'Isn\'t bothered about humidity levels', 
          soil: 'The soil mix must be free draining and not have a great deal of rich organic material', 
          lvl: '', 
          more: '', 
          img: ''
        },
        {
          id: 18,
          common_name: 'Spider Plant', 
          species_name: 'Chlorophytum comosum', 
          water: 'Prefers moist but never wet soils. Can tolerate dry conditions', 
          light: 'Bright indirect light', 
          temp: '13°C–27°C', 
          humidity: 'Loves humidity', 
          soil: 'Grow in a soil-based, well-draining potting mix', 
          lvl: 'Beginner', 
          more: '', 
          img: ''
        },
        {
          id: 19,
          common_name: 'Pink Bubbles', 
          species_name: 'Pink callisia repens', 
          water: 'Likes to be watered regularly, keep the soil moist. But don\'t leave it sitting in water. Water a little less during winter months', 
          light: 'Will thrive in bright indirect sunlight', 
          temp: '>16°C', 
          humidity: 'Prefers a warm and humid environment', 
          soil: 'Prefers a well-draining acidic soil', 
          lvl: '', 
          more: '', 
          img: ''
        },
        {
          id: 20,
          common_name: 'Silver Lady Fern ', 
          species_name: 'Blechnum gibbum', 
          water: 'Water frequently during the warmer months. Slightly reduce watering in colder months', 
          light: 'Prefers bright light with partial shade', 
          temp: '10°C-25°C', 
          humidity: 'Requires high humidity during its growth period', 
          soil: 'Thrives in compost-enriched, moist, and slightly acidic well-draining soil', 
          lvl: '', 
          more: 'Air purifier', 
          img: ''
        },
      ]);
    });
};
