
exports.seed = function(knex) {
  return knex('plants').del()
    .then(function () {
      return knex('plants').insert([
        {
          id: 1, 
          common_name: 'Monstera', 
          species_name: 'Monstera deliciosa', 
          water: 'Once a week',
          light: 'Thrives in bright to medium indirect light', 
          temp: '18°C-30°C',
          humidity: 'Adaptable, but prefers humid conditions so mist once a week', 
          soil: 'Requires rich, nutrient rich dense soil that holds moisture', 
          lvl: 'beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image1.jpeg'
        },
        {
          id: 2, 
          common_name: 'Fittonia', 
          species_name: 'Fittonia albivenis', 
          water: 'Water once a week but monitor carefully as will develop yellowed limp leaves if overwatered', 
          light: 'Filtered indirect sun or part shade', 
          temp: '16 - 26°C', 
          humidity: 'Likes to be moist so mist regularly', 
          soil: 'Moist, well-draining soil', 
          lvl: 'intermediate', 
          more: '', 
          img: 'https://htense.github.io/images/image2.jpeg'
        },
        {
          id: 3,
          common_name: 'Yucca', 
          species_name: 'Yucca', 
          water: 'Prefer to be on the dry side, in general allow the top half of the soil to become dry before watering', 
          light: 'Likes bright, indirect sunlight', 
          temp: '13 - 27°C ', 
          humidity: 'Does not appreciate too much humidity, so light infrequent misting will do', 
          soil: 'Sandy', 
          lvl: 'Beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image3.jpeg'
        },
        {
          id: 4,
          common_name: 'Peace Lily', 
          species_name: 'Spathiphyllum wallisii', 
          water: 'Consistency is key - keep moist but not wet', 
          light: 'Bright filtered light to full-shade', 
          temp: '16 - 21°C+', 
          humidity: 'Enjoys high humidity so mist frequently', 
          soil: 'Moist, rich, free-draining soil, and repot annually', 
          lvl: 'Beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image4.jpeg'
        },
        {
          id: 5,
          common_name: 'Aloe', 
          species_name: 'Aloe Vera', 
          water: 'Minimal, soil should be completely dry before needing to water', 
          light: 'Bright indirect sunlight', 
          temp: '13 - 27°C', 
          humidity: "Doesn't require extra misting", 
          soil: 'Needs a well draining potting mix such as those made for cacti and succulents with excellent drainage', 
          lvl: 'beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image5.jpeg'
        },
        {
          id: 6,
          common_name: 'Rubber Plant', 
          species_name: 'Ficus Elastica', 
          water: 'Every 1-2 weeks, allow soil to dry out between watering', 
          light: 'medium-bright indirect light', 
          temp: '18°C-30°C', 
          humidity: 'Consistent humidity is key, if in dry environment mist regularly', 
          soil: 'well-draining and well-aerated potting soil ', 
          lvl: 'beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image7.jpeg'
        },
        {
          id: 7,
          common_name: 'Snake Plant', 
          species_name: 'Sansevieria trifasciata', 
          water: 'Water only when soil is completely dry', 
          light: 'Bright, indirect sunlight. Can tolerate direct sunlight', 
          temp: '10°C+', 
          humidity: 'Low humidity', 
          soil: 'A soilless potting mixture containing organic and inorganic materials instead of soil does wonders for snake plants because they can be prone to rotting. A regular soil mixture will work well too as long as you make sure the mixture is well-drained, free draining soil', 
          lvl: 'beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image8.jpeg'
        },
        {
          id: 8,
          common_name: 'English Ivy', 
          species_name: 'Hedera helix', 
          water: 'Sensitive to overwatering so ensure at least one inch of topsoil is dry before watering', 
          light: 'bright filtered to low ligh', 
          temp: '10-21°C', 
          humidity: "Like moist environments but not direct misting. Try adding pebbles to a saucer, then add water. Set your ivy on the pebbles and the water will evaporate, raising the humidity around the plant", 
          soil: 'Fertile, moist, but well-drained soil', 
          lvl: 'Intermediate', 
          more: '', 
          img: 'https://htense.github.io/images/image9.jpeg'
        },
        {
          id: 9,
          common_name: 'Maidenhair fern', 
          species_name: 'Adiantum', 
          water: "Water whenever the top of the soil feels even slightly dry. Doesn't like to be even slighty dry so commit to checking whether watering is required everyday", 
          light: 'No direct light, filtered medium light is perfect', 
          temp: '16-21°C', 
          humidity: 'Likes high humidity, so mist frequently and set on a water-filled pebble tray', 
          soil: 'Moist but well-draining potting soil', 
          lvl: 'Intermediate - advanced', 
          more: '',
          img: 'https://htense.github.io/images/image10.jpeg'
        },
        {
          id: 10,
          common_name: 'String Of Pearls', 
          species_name: 'Senecio rowleyanus', 
          water: 'Infrequent, allow the top inch of soil to dry out completely before watering', 
          light: 'Bright filtered light', 
          temp: '15-27°C', 
          humidity: 'Average to dry humidity', 
          soil: 'Good quality, well draining potting soil', 
          lvl: 'Beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image11.jpeg'
        },
        {
          id: 11,
          common_name: 'Madagascar dragon tree', 
          species_name: 'Dracaena Marginata', 
          water: 'Not too regular, keeping the soil slightly moist is key', 
          light: 'Bright filtered light', 
          temp: '18°- 24°C', 
          humidity: 'Likes moderately humid conditions, to keep moist set pot onto a tray filled with pebbles', 
          soil: 'Nutrient rich well draining potting mix', 
          lvl: 'Beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image12.jpeg'
        },
        {
          id: 12,
          common_name: 'Tillandsia (air plants)', 
          species_name: 'epiphytes or bromeliads', 
          water: 'Every 1-2 weeks, soak in room temp tap water for 10mins, then gently shake excess water from your plant. Turn it upside down and place it on a towel to dry in a bright space. This is very important! Air plants will quickly rot if they are allowed to stand in excess water for too long without drying. Regular misting is also encouraged', 
          light: 'Bright indirect light', 
          temp: '15-30°C', 
          humidity: 'Moderate humidity', 
          soil: 'No soil, hence the name Air Plant as they can thrive on nutrients provied from the surrounding air' , 
          lvl: 'Intermediate', 
          more: '', 
          img: 'https://htense.github.io/images/image13.jpeg'
        },
        {
          id: 13,
          common_name: 'Devil’s Ivy', 
          species_name: 'Epipremnum pinnatum', 
          water: 'Approximately once a week or when the top inch or two of soil feels dry', 
          light: 'Situate it in an area that receives filtered sunlight or bright artificial light', 
          temp: '15°C-29°C', 
          humidity: 'Does well at normal (about 40% - 60%) humidity levels', 
          soil: 'An all-purpose, peaty potting mix that drains well', 
          lvl: '', 
          more: '', 
          img: 'https://htense.github.io/images/image14.jpeg'
        },
        {
          id: 14,
          common_name: 'Fiddle Leaf Fig', 
          species_name: 'Ficus lyrata', 
          water: 'Allow the potting mix or soil to dry out between each watering', 
          light: 'Requires bright, filtered light', 
          temp: '>16°C', 
          humidity: 'Aim for a humidity level between 30% and 65%.', 
          soil: 'Fast draining, well aerated soils are ideal', 
          lvl: 'Intermediate - Advanced', 
          more: '', 
          img: 'https://htense.github.io/images/image15.jpeg'
        },
        {
          id: 15,
          common_name: 'Zanzibar Gem', 
          species_name: 'Zamioculcas zamifolia', 
          water: 'Let the soil dry out in between waterings so as to ensure the stems don\'t rot, water less in the cooler months', 
          light: 'It’s happy in low light conditions but will thrive in indirect bright light', 
          temp: '>16°C', 
          humidity: 'Prefers a humid environment for optimal growth', 
          soil: 'Use a good quality potting mix that is fast draining', 
          lvl: '', 
          more: '', 
          img: 'https://htense.github.io/images/image16.jpeg'
        },
        {
          id: 16,
          common_name: 'succulents', 
          species_name: 'echeverias', 
          water: 'once per fortnight', 
          light: 'direct', 
          temp: 'warm', 
          humidity: 'mid', 
          soil: 'well-drained', 
          lvl: 'Beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image1.jpeg'
        },
        {
          id: 17,
          common_name: 'Sweetheart Plant', 
          species_name: 'Hoya kerrii', 
          water: 'Wait until the soil has dried out a little and then water again', 
          light: 'Will thrive in both sunny and shady spots, but dislikes direct sun in summer. An east or west facing window suits it', 
          temp: '18°C - 27°C', 
          humidity: 'Isn\'t bothered about humidity levels', 
          soil: 'The soil mix must be free draining and not have a great deal of rich organic material', 
          lvl: '', 
          more: '', 
          img: 'https://htense.github.io/images/image2.jpeg'
        },
        {
          id: 18,
          common_name: 'Spider Plant', 
          species_name: 'Chlorophytum comosum', 
          water: 'Prefers moist but never wet soils. Can tolerate dry conditions', 
          light: 'Bright indirect light', 
          temp: '13°C–27°C', 
          humidity: 'Loves humidity', 
          soil: 'Grow in a soil-based, well-draining potting mix', 
          lvl: 'Beginner', 
          more: '', 
          img: 'https://htense.github.io/images/image3.jpeg'
        },
        {
          id: 19,
          common_name: 'Pink Bubbles', 
          species_name: 'Pink callisia repens', 
          water: 'Likes to be watered regularly, keep the soil moist. But don\'t leave it sitting in water. Water a little less during winter months', 
          light: 'Will thrive in bright indirect sunlight', 
          temp: '>16°C', 
          humidity: 'Prefers a warm and humid environment', 
          soil: 'Prefers a well-draining acidic soil', 
          lvl: '', 
          more: '', 
          img: 'https://htense.github.io/images/image4.jpeg'
        },
        {
          id: 20,
          common_name: 'Silver Lady Fern ', 
          species_name: 'Blechnum gibbum', 
          water: 'Water frequently during the warmer months. Slightly reduce watering in colder months', 
          light: 'Prefers bright light with partial shade', 
          temp: '10°C-25°C', 
          humidity: 'Requires high humidity during its growth period', 
          soil: 'Thrives in compost-enriched, moist, and slightly acidic well-draining soil', 
          lvl: '', 
          more: 'Air purifier', 
          img: 'https://htense.github.io/images/image5.jpeg'
        },
      ]);
    });
};
